baseurl = "/"
title = "Streeling"
theme = "ghostwriter2"
languageCode = "en-us"
copyright = "Jarod G.R. Meng"
disqusShortname = ""
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown", "_files$", "_cache$"]

[Author]
    name = "Jarod G.R. Meng"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "Streeling"
    description = "[There has to be] A place for futile thoughts and dismal sciences..."
    github = "https://github.com/jarodmeng"
    email = "genrong.meng@gmail.com"
    dateFormat = "Mon, Jan 2, 2006"
    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Blog"
    url = "/post/"
    weight = 1

[[menu.main]]
    name = "Contact"
    url = "/page/contact/"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 3
